env: dev # dev, user-local, samir-local ... (don't use production environment on local development)
appPath: !appPath # don't override this
appName: "phalcon-4"

# application dirs
dirs:
  tmp: !appPath 'tmp' # this will parsed as: /[home-path]/tmp

sentry:
  dsn: 'https://x@sentry.io/xx' # sentry report uri

redis:
  host: "10.10.1.3"
  port: 6379

database:
  db1:
    adapter:  "pgsql" # available adapters: mysql, pgsql, sqlite
    host:     "10.10.1.5"
    dbname:   "samir"
    port:     5432
    username: "samir"
    password: "secret"
    charset:  "utf-8"