env: dev # dev, user-local, samir-local ... (don't use production environment on local development)
appPath: !appPath # don't override this

# application dirs
dirs:
  tmp: !appPath 'tmp' # this will parsed as: /[home-path]/tmp

sentry:
  dsn: 'https://[...]@sentry.io/[...]' # sentry report uri

database:
  db1:
    adapter:  "pgsql" # available adapters: mysql, pgsql, sqlite
    host:     "10.10.1.5"
    dbname:   "samir"
    port:     5432
    username: "samir"
    password: "secret"
    charset:  "utf-8"