<?php

use PHPUnit\Framework\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase {
    protected function setUp() : void {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}